
/**************************************************************
 *	
 *	dead, 8 bit, 11025Hz,
 *	2 channel, 28307 bytes/channel
 *	Total Size: 2 * 28307 + 4 (header) = 56658 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\paula\Documents\College\Junior Year\Media Device Arch\m05\dead.wav
 *	Time-stamp: Fri Apr 26 09:50:09 2019
 *	
 **************************************************************/

#ifndef __DEADH__
#define __DEADH__

#define DEADFREQ 11025
#define DEADLEN 28307

extern const unsigned char dead_c1[28307];
extern const unsigned char dead_c2[28307];

#endif /* __DEADH__ */
