
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	2 channel, 1918944 bytes/channel
 *	Total Size: 2 * 1918944 + 4 (header) = 3837932 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\paula\Documents\College\Junior Year\Media Device Arch\m04\gameSong.wav
 *	Time-stamp: Thu Apr 18 07:38:02 2019
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 1918944

extern const unsigned char gameSong_c1[1918944];
extern const unsigned char gameSong_c2[1918944];

#endif /* __GAMESONGH__ */
