
/**************************************************************
 *	
 *	sparkle, 8 bit, 11025Hz,
 *	2 channel, 24801 bytes/channel
 *	Total Size: 2 * 24801 + 4 (header) = 49646 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\paula\Documents\College\Junior Year\Media Device Arch\m05\sparkle.wav
 *	Time-stamp: Fri Apr 26 09:49:35 2019
 *	
 **************************************************************/

#ifndef __SPARKLEH__
#define __SPARKLEH__

#define SPARKLEFREQ 11025
#define SPARKLELEN 24801

extern const unsigned char sparkle_c1[24801];
extern const unsigned char sparkle_c2[24801];

#endif /* __SPARKLEH__ */
